name: .NET

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
            7.0.x
            8.0.x

    # Add NuGet Sources

    - name: Create Local NuGet Directory
      run: mkdir ~/nuget

    - name: Add Local Nuget Source
      run: dotnet nuget add source ~/nuget

    - name: Add GarageGroup NuGet Source
      run: >
        dotnet nuget add source ${{ vars.GG_NUGET_SOURCE_URL }}
        -n garage
        -u ${{ secrets.GG_NUGET_SOURCE_USER_NAME }}
        -p ${{ secrets.GG_NUGET_SOURCE_USER_PASSWORD }}
        --store-password-in-clear-text

    # DbRequest.Generator

    - name: Restore DbRequest.Generator
      run: dotnet restore ./src/*/DbRequest.Generator.csproj

    - name: Build DbRequest.Generator
      run: dotnet build ./src/*/DbRequest.Generator.csproj --no-restore  -c Release

    - name: Pack DbRequest.Generator
      run: dotnet pack ./src/*/DbRequest.Generator.csproj --no-restore -o ~/nuget  -c Release

    # DbRequest

    - name: Restore DbRequest
      run: dotnet restore ./src/*/DbRequest.csproj

    - name: Build DbRequest
      run: dotnet build ./src/*/DbRequest.csproj --no-restore  -c Release

    - name: Pack DbRequest
      run: dotnet pack ./src/*/DbRequest.csproj --no-restore -o ~/nuget  -c Release

    # DbRequest.Test

    - name: Restore DbRequest.Test
      run: dotnet restore ./src/*/DbRequest.Test.csproj

    - name: Test DbRequest.Test
      run: dotnet test ./src/*/DbRequest.Test.csproj --no-restore  -c Release

    # Push

    - name: Push Packages
      if: ${{ github.ref == 'refs/heads/main' }}
      run: >
        dotnet nuget push "../../../nuget/*.nupkg"
        -s ${{ vars.GG_NUGET_SOURCE_URL }}
        -k ${{ secrets.GG_NUGET_SOURCE_USER_PASSWORD }}
        --skip-duplicate