name: .NET

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
            6.0.x
            7.0.x
            8.0.x

    # Add NuGet Sources

    - name: Create Local NuGet Directory
      run: mkdir ~/nuget

    - name: Add Local Nuget Source
      run: dotnet nuget add source ~/nuget

    - name: Add GarageGroup NuGet Source
      run: >
        dotnet nuget add source ${{ vars.GG_NUGET_SOURCE_URL }}
        -n garage
        -u ${{ secrets.GG_NUGET_SOURCE_USER_NAME }}
        -p ${{ secrets.GG_NUGET_SOURCE_USER_PASSWORD }}
        --store-password-in-clear-text

    # DbEntity.Generator

    - name: Restore DbEntity.Generator
      run: dotnet restore ./src/*/*/DbEntity.Generator.csproj

    - name: Build DbEntity.Generator
      run: dotnet build ./src/*/*/DbEntity.Generator.csproj --no-restore  -c Release

    - name: Pack DbEntity.Generator
      run: dotnet pack ./src/*/*/DbEntity.Generator.csproj --no-restore -o ~/nuget  -c Release

    # DbEntity.Generator.Test

    - name: Restore DbEntity.Generator.Test
      run: dotnet restore ./src/*/*/DbEntity.Generator.Test.csproj

    - name: Test DbEntity.Generator.Test
      run: dotnet test ./src/*/*/DbEntity.Generator.Test.csproj --no-restore  -c Release

    # Api.Core.DbRequest

    - name: Restore Api.Core.DbRequest
      run: dotnet restore ./src/*/*/DbRequest.csproj

    - name: Build Api.Core.DbRequest
      run: dotnet build ./src/*/*/DbRequest.csproj --no-restore  -c Release

    - name: Pack Api.Core.DbRequest
      run: dotnet pack ./src/*/*/DbRequest.csproj --no-restore -o ~/nuget  -c Release

    # Api.Core.DbRequest.Test

    - name: Restore Api.Core.DbRequest.Test
      run: dotnet restore ./src/*/*/DbRequest.Test.csproj

    - name: Test Api.Core.DbRequest.Test
      run: dotnet test ./src/*/*/DbRequest.Test.csproj --no-restore  -c Release

    # Push

    - name: Push Packages
      if: ${{ github.ref == 'refs/heads/main' }}
      run: >
        dotnet nuget push "../../../nuget/*.nupkg"
        -s ${{ vars.GG_NUGET_SOURCE_URL }}
        -k ${{ secrets.GG_NUGET_SOURCE_USER_PASSWORD }}
        --skip-duplicate